# Site settings
title: A blog about lorem ipsum dolor sit amet
description: A blog about lorem ipsum dolor sit amet
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: loreandstory
user_description: I'm a dedicated, innovative, hard-working programmer who holds a degree in Mechanical Engineering and worked for years debugging printers rather than code. I fell in love with programming and have been learning and practicing ever since. My main focus is currently back end development using Ruby, though I do have some knowledge of front end web development and have been tinkering with Rust. I also enjoy making SVG art in Inkscape.

user_title: Software Developer
email: loreandstory@outlook.com
github_username: loreandstory

# Google-analytics
google-analytics:
  id: ""

# Sass
sass:
  sass_dir: _sass

exclude: ['package.json', 'src' , 'node_modules']
